onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma

minimumReleaseAge: 10080

updateConfig:
  ignoreDependencies:
    - remix-auth
    - remix-auth-google
